In [1]:
import numpy as np

In [4]:
#Basics
a=np.array([1,2,3])
print(a)

[1 2 3]


In [36]:
b=np.array([[1,2,3,8],[4,5,6,8],[7,8,9,8]],dtype='int32')
print(b)

[[1 2 3 8]
 [4 5 6 8]
 [7 8 9 8]]


In [19]:
#dimension  of a numpy array
a.ndim
b.ndim

2

In [22]:
#shape of a numpy array
np.shape(b)

(3, 4)

In [23]:
a.shape

(3,)

In [24]:
b.shape

(3, 4)

In [34]:
#get Type
b.dtype

dtype('int64')

In [37]:
#get Size
b.itemsize

4

In [39]:
#get total size
a.nbytes

12

In [40]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [49]:
a[-1,-7]

8

In [51]:
a[1,6]

14

In [52]:
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [60]:
a[1,3:6]

array([11, 12, 13])

In [65]:
a[:,1:5]

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

In [69]:
#star, end stepsize
a[0,1:6:2]

array([2, 4, 6])

In [70]:
a[1,5]=20

In [71]:
a


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [72]:
a[:,2]=50000


In [73]:
a

array([[    1,     2, 50000,     4,     5,     6,     7],
       [    8,     9, 50000,    11,    12,    20,    14]])

In [77]:
a[1,:]=9999
a

array([[    1,     2, 50000,     4,     5,     6,     7],
       [ 9999,  9999,  9999,  9999,  9999,  9999,  9999]])

In [83]:
#3D example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
b[1,1,1]

8

In [98]:
#all zeroes matrix
np.zeros((2,3,4,5),dtype='int16')

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int16)

In [99]:
#all ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [105]:
np.ones((2,3,1),dtype="int32")

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [110]:
#any other number
np.full((2,3,4),99,dtype='float32')

array([[[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]],

       [[99., 99., 99., 99.],
        [99., 99., 99., 99.],
        [99., 99., 99., 99.]]], dtype=float32)

In [113]:
#any other number (full like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [116]:
#intialize array with random number
np.random.rand(4,2)

array([[0.85730991, 0.55990621],
       [0.17353804, 0.46142329],
       [0.78818874, 0.94184214],
       [0.13211619, 0.61144216]])

In [118]:
np.random.random_sample(a.shape)

array([[0.24442245, 0.83116042, 0.17071414, 0.20287065, 0.34972631,
        0.898527  , 0.28418977],
       [0.50406065, 0.69309628, 0.75872901, 0.75204874, 0.23562921,
        0.4255585 , 0.85861301]])

In [132]:
#random integer values
np.random.randint(-8686,60,size=(3,3))

array([[-5940,  -725, -4248],
       [-5248, -4584, -7140],
       [   30, -6359,  -859]])

In [134]:
#indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [140]:
#repeat an array
arr=np.array([[1,2,3]])
r=np.repeat(arr,3,axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [143]:
#exercise
output=np.ones((5,5))
print((output))
z=np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [144]:
z[1,1]=9

In [145]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [148]:
output[1:4,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

be carefull while copying array

In [155]:
a=np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

In [156]:
b[0]=100

In [158]:
b

array([100,   2,   3])

Lets learn some Mathematics now. :)

In [159]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [162]:
a+2

array([3, 4, 5, 6])

In [163]:
a-2

array([-1,  0,  1,  2])

In [164]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [165]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [166]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [169]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [175]:
val=np.array([0,45,60,90])
s=np.cos(val)
s

array([ 1.        ,  0.52532199, -0.95241298, -0.44807362])

Linear Algebra

In [183]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
m=np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [181]:
Determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [184]:
np.linalg.det(m)

0.0

In [185]:
#### statisitcs

In [187]:
stats=np.array([[1,2,-3],[4,5,6]])
np.min(stats)

-3

In [193]:
np.max(stats)

6

In [195]:
np.sum(stats)

array([5, 7, 3])

reorganising array

In [208]:
before=np.array([[1,2,3,5],[4,5,6,6]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 5]
 [4 5 6 6]]
[[[1 2]
  [3 5]]

 [[4 5]
  [6 6]]]


In [211]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2,v1])



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [213]:
#horizantal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2,h1,h2])



array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.]])

Miscellaneous 

Load Data from File

In [215]:
filedata=np.genfromtxt('datasets/data.txt',delimiter=',')

filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

## Boolean Masking and Advanced indexing

In [216]:
filedata>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [217]:
filedata[filedata>5]

array([ 6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,
        9., 10.,  6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 10.,  6.,
        7.,  8.,  9., 10.])

In [222]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [223]:
a>3

array([False, False, False,  True,  True,  True,  True,  True,  True])